### PR TITLE
remove azimuth angle QC in convertor

### PR DESCRIPTION
**Pull request by hailingz**
The azimuth angle QC check is removed in GNSSRO IODA convertor because operators should check the azimuth angle when needed. Actually azimuth angles are only required in 2D operators.  RO data without azimuth angle should not be rejected in data processing.

https://github.com/jcsda/aop20/issues/58

### CODE REVIEW

**Comment by hailingz** [comment]
@srherbener 
The Travis CI log shows iodaconv_marine_coding_norms failed. Not sure how to fix.  Thanks,

**Comment by hailingz** [comment]
@srherbener 

Thank you so much for your review and explanation.

**Comment by srherbener** [comment]
@hailingz, I merged in develop, which contains the fix for the marine coding norms test failure. The CI testing issues have been fixed. We should see the tests pass now.

**Comment by markjolah** [comment]
OK with me.

**Pull request merged**
