### PR TITLE
Change ozone variable name

### PR DESCRIPTION
**Pull request by emilyhcliu**
Chagne ozone variable (geoval) name from **mass_concentration_of_ozone _in_air** to **mole_fraction_of_ozone_in_air**.  
The change is to make the name of the ozone geoval to be consistent with the name from fv3 model.

Note: The ozone observation name has been changed to "integrated_layer_ozone_in_air" in earlier PR.

### CODE REVIEW

**Comment by HaixiaLiu-NOAA** [comment]
@emilyhcliu glad to see you have made these changes. Looks good to me. I approved it.

**Review by HaixiaLiu-NOAA — APPROVED** [review]

**Review by markjolah — APPROVED** [review]

**Comment by emilyhcliu** [comment]
@srherbener Do you have time to take a quick look at this PR and see if it is good to be merged to develop?
Thanks a lot!

**Comment by srherbener** [comment]
Sorry about the delay

**Comment by emilyhcliu** [comment]
@srherbener Thanks a lot!

**Pull request merged**
