### PR TITLE
Feature/bufr

### PR DESCRIPTION
**Pull request by YanHao-NOAA**
- Option "-l " was added to choose the yaml file.
- Option "-m" was modified to allow user to dump a few message or the whole file.
- Created yaml files of several bufr tanks and put all the yaml files in /config. The yaml file's name is similar to the bufr tank name, e.g. b001xx007, the yaml file is named NC001007.yaml.
- Updated ioda-converters/src/ncep/CMakeLists.txt to enable the ecbuild to put yaml files in the correct directory.
- Updated README.
- Added ISO 8601 timestamp.
- A test file was created.
- This package went through ecbuild--make--make install--ctest.

### CODE REVIEW

**Comment by flampouris** [comment]
@YanHao-NOAA all the automated tests have failed. Please check why the build fails.

**Comment by YanHao-NOAA** [comment]
I did ecbuild before feature/bufr merged with develop, but did not redo ecbuild after merged with develop. I will check this after Hera come back.

**Comment by YanHao-NOAA** [comment]
Jong fixed the python package problem on Hera this morning:
He mentioned: "I finished to complete all python package installation to the following anaconda3-save on hera. You are already using py-ncepbufr from this anaconda3. So, just to point out that you can use modulefiles in save directory now instead of save_test.
module use -a /scratch2/NCEPDEV/marineda/Jong.Kim/save/modulefiles/
module load anaconda/3.15.1"
I didn't change any of my codes, rebuild and tested my codes again, now 100% test passed.
[Yan.Hao@hfe08 build]$ ctest
Test project /scratch2/NCEPDEV/marine/Yan.Hao/IODA_NEW/build
      Start  1: iodaconv_lib-python_coding_norms
 1/25 Test  #1: iodaconv_lib-python_coding_norms .....   Passed    0.68 sec
      Start  2: iodaconv_gsi-ncdiag_coding_norms
 2/25 Test  #2: iodaconv_gsi-ncdiag_coding_norms .....   Passed    0.69 sec
      Start  3: iodaconv_marine_coding_norms
 3/25 Test  #3: iodaconv_marine_coding_norms .........   Passed    0.71 sec
      Start  4: iodaconv_chem_coding_norms
 4/25 Test  #4: iodaconv_chem_coding_norms ...........   Passed    0.43 sec
      Start  5: iodaconv_ncep_coding_norms
 5/25 Test  #5: iodaconv_ncep_coding_norms ...........   Passed    0.65 sec
      Start  6: iodaconv_wrfda-ncdiag_coding_norms
 6/25 Test  #6: iodaconv_wrfda-ncdiag_coding_norms ...   Passed    0.41 sec
      Start  7: test_iodaconv_gds2_sst_l2p
 7/25 Test  #7: test_iodaconv_gds2_sst_l2p ...........   Passed    0.50 sec
      Start  8: test_iodaconv_gds2_sst_l3u
 8/25 Test  #8: test_iodaconv_gds2_sst_l3u ...........   Passed    0.53 sec
      Start  9: test_iodaconv_smap_sss
 9/25 Test  #9: test_iodaconv_smap_sss ...............   Passed    0.40 sec
      Start 10: test_iodaconv_rads_adt
10/25 Test #10: test_iodaconv_rads_adt ...............   Passed    0.39 sec
      Start 11: test_iodaconv_godae_prof
11/25 Test #11: test_iodaconv_godae_prof .............   Passed    0.43 sec
      Start 12: test_iodaconv_godae_ship
12/25 Test #12: test_iodaconv_godae_ship .............   Passed    0.45 sec
      Start 13: test_iodaconv_godae_trak
13/25 Test #13: test_iodaconv_godae_trak .............   Passed    0.41 sec
      Start 14: test_iodaconv_hgodas_insitu
14/25 Test #14: test_iodaconv_hgodas_insitu ..........   Passed    0.35 sec
      Start 15: test_iodaconv_hgodas_sst
15/25 Test #15: test_iodaconv_hgodas_sst .............   Passed    0.32 sec
      Start 16: test_iodaconv_argoclim
16/25 Test #16: test_iodaconv_argoclim ...............   Passed    0.40 sec
      Start 17: test_iodaconv_cryosat2
17/25 Test #17: test_iodaconv_cryosat2 ...............   Passed    0.56 sec
      Start 18: test_iodaconv_cryosat2_DBL
18/25 Test #18: test_iodaconv_cryosat2_DBL ...........   Passed   12.63 sec
      Start 19: test_iodaconv_viirs_jpss1_oc_l2
19/25 Test #19: test_iodaconv_viirs_jpss1_oc_l2 ......   Passed    0.66 sec
      Start 20: test_iodaconv_modis_aqua_oc_l2
20/25 Test #20: test_iodaconv_modis_aqua_oc_l2 .......   Passed    0.65 sec
      Start 21: test_iodaconv_gsidiag_conv_uv
21/25 Test #21: test_iodaconv_gsidiag_conv_uv ........   Passed    0.35 sec
      Start 22: test_iodaconv_gsidiag_conv
22/25 Test #22: test_iodaconv_gsidiag_conv ...........   Passed    0.38 sec
      Start 23: test_iodaconv_gsidiag_rad
23/25 Test #23: test_iodaconv_gsidiag_rad ............   Passed    0.44 sec
      Start 24: test_iodaconv_wrfdadiag_rad
24/25 Test #24: test_iodaconv_wrfdadiag_rad ..........   Passed    0.34 sec
      Start 25: test_iodaconv_viirs_aod
25/25 Test #25: test_iodaconv_viirs_aod ..............   Passed    0.36 sec

100% tests passed, 0 tests failed out of 25

Label Time Summary:
iodaconv    =  24.12 sec*proc (25 tests)
script      =  24.12 sec*proc (25 tests)

Total Test time (real) =  24.14 sec

**Comment by flampouris** [comment]
@YanHao-NOAA the tests at Travis CI (which is the standard testing infrastructure) fail. To see the error check here https://travis-ci.com/github/JCSDA/ioda-converters/builds/169142118 at the very bottom of the webpage.

The reasons have been identified at #282 please follow the conversation / recommendationd and try to provide a solution if possible.

**Comment by srherbener** [comment]
@YanHao-NOAA, I've submitted a PR (#283) that addresses the test failures you are seeing with this PR. No need to do fix anything in this PR.

If you want to try the fix in PR #283 now, simply merge the bugfix/marine-coding-norm branch into this PRs branch (feature/bufr) and push (``git flow ... publish ...``) to github. Or if you are okay waiting, you can wait until PR #283 gets merged into develop and then merge develop into this PRs branch.

**Comment by srherbener** [comment]
@YanHao-NOAA, I merged in develop which contains the fix for the marine coding norm error. The new version of pycodestyle also found a new error in one of the other ncep scripts so I fixed that as well. The CI testing issues have been fixed so you should see all the test passing now.

**Comment by YanHao-NOAA** [comment]
@srherbener Thank you, I will merge develop to feature/bufr.

**Comment by flampouris** [comment]
Thank you @YanHao-NOAA  and @srherbener !

**Pull request merged**
