### PR TITLE
Feature/cryosat freeboard

### LINKED ISSUE #234: GNSSRO test failing in develop
Just reporting that test_iodaconv_gnssro_bufr_conv fails in develop. @hailingz , I assigned you, since it seems you wrote the converter, but feel free to ignore or assign somebody else obviously.

### PR DESCRIPTION
**Pull request by YanHao-NOAA**
Description: 
Created IODA converter for Cryosat-2 ice freeboard NetCDF-4 data sets.
Modified CMakeLists.txt to include cryosat ice.
Added test case:  testinput/cryosat2_L2_test.nc ;  testoutput/cryosat2_L2.nc
Issues:
In order to be able to use nc.MFDataset, we have to transform NetCDF-4 into Net_CDF-4 classic first. (Solved by using nccopy).
Test:
checkout Feature/cryosat freeboard,  ecbuild, make, make install, ctest.

Closes #234

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@srherbener, @hailingz  The **test_iodaconv_gnssro_bufr_conv** ctest is failing in develop. @YanHao-NOAA , I suggest you comment out the failing test in your branch and submit an issue.

**Comment by srherbener** [comment]
We may need to comment out the test as a last resort, but I'd like to try and debug first to see if there's a relatively quick fix. I made myself and @markjolah the assignees for #234 and I can help debug initially. The build and test of the GNSSRO converter is working in many places so I hope this is something easy to fix. Let's continue the discussions in #234.

Thanks for your patience with this!

**Comment by YanHao-NOAA** [comment]
Base on your discussions, I am not sure if I should leave this GNSSRO test alone at this moment, or do you prefer me to comment it out now? Thanks.

**Comment by srherbener** [comment]
@YanHao-NOAA, let's plan to leave the GNSSRO test alone for now. I've discovered a solution, which is to use ecbuild 3.1.0, but I need to coordinate this with the container build process.

If it turns out that it will take a while to test and verify all software packages will work with upgrading ecbuild to 3.1.0 in the containers, then we can change our plan.

**Comment by srherbener** [comment]
I just added a commit with a workaround in the CMake configuration that gets the Travis-CI build/test working. @mer-a-o has a new PR in place (#235) which will fix the AWS intel test failure. The AWS Intel test failure is a CodeBuild environment setup issue and not related to the CMake configuration or the source code in this repository so I think we are good to go with Travis-CI and AWS GNU passing checks.

There is no need to comment out the test_iodaconv_gnssro_bufr_conv test now.

Please continue with the reviewing now, and thanks for your patience!

**Comment by flampouris** [comment]
@srherbener <https://github.com/srherbener>  thank you.

**Comment by srherbener** [comment]
All of the containers have been updated to use ecbuild 3.1.0 which makes my workaround unnecessary. I've removed my workaround, and the build and tests work on my iMac with both Singularity and CharlieCloud. @mer-a-o is updating Travis-CI to use ecbuild 3.1.0 as well. She should be updating soon with a commit to this PR which gets Travis-CI working again.

**Comment by mer-a-o** [comment]
I updated Travis-CI and AWS gnu tests to use the latest docker container. Intel tests will pass after https://github.com/JCSDA/ioda-converters/pull/235 is merged.

**Comment by srherbener** [comment]
I just merged the AWS intel test fix PR into develop, then merged develop into this PR. We should see all checks pass now.

**Comment by srherbener** [comment]
Yay! All checks pass. The only thing left is to address the test file size (@guillaumevernieres review comment). Thanks everyone for your help with this PR!

**Comment by srherbener** [comment]
Merged in develop again which added the AWS Clang test (which passes).

**Comment by jkbk2004** [comment]
All looks good!

**Comment by srherbener** [comment]
@guillaumevernieres, the new test file is about 1/10th the size of the original (1.4M vs 12M). Does this reduction sound good with you? Thanks!

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres, the new test file is about 1/10th the size of the original (1.4M vs 12M). Does this reduction sound good with you? Thanks!

I don't think we need 6000 + obs for the testing. @YanHao-NOAA , could you reduce your test file to a few obs? Less than a 100 would be sufficient.

**Comment by YanHao-NOAA** [comment]
Further downsized the test files.

**Pull request merged**
