### PR TITLE
Feature/bufr2nc fortran

### PR DESCRIPTION
**Pull request by hu5970**
This fortran convertor can decode many datatypes in prepbufr and encode them into different netcdf files for UFO to read.

To compile the code, conduct 
1) make (path to this directory)
2) make

To run the executable:
1) edit the namelist.input (sample in this directory)
2) ./get_obs.exe

The sample run directory on Cheyenne:
/glade/p/ral/jntp/mhu/jedi/dataproc/code/convert_bufr2nc/build2/bin

### CODE REVIEW

**Comment by srherbener** [comment]
@hu5970, my apologies that this got put aside for so long. I'm going to change this to a DRAFT PR and have some reviewers look at it to see if there is interest in it. Are you still interested in using this with your work?

@aerorahul, @markjolah this is a Fortran BUFR to netcdf converter that @hu5970 contributed a ways back. At the time, it was supposed to be the start of a generic converter that would run fast (compiled code) and be configurable from a namelist file (probably would want a YAML file eventually). Please take a look and see if this is of interest.

Thanks!

**Comment by aerorahul** [comment]
@hu5970 @srherbener I can take a look next week.

**Comment by srherbener** [comment]
@aerorahul Thanks!

**Comment by srherbener** [comment]
Due to the lack of activity with this PR, I'm going to close it for now. Please feel free to reopen if you are interested in using this converter.

**Pull request closed without merging**
