### PR TITLE
Feature/giirs ssec

### PR DESCRIPTION
**Pull request by markjolah**
This is a draft PR with a giirs converter contributed by @weihanucar.  I took the provided code and cleaned it up to more logically use the class concept.  
* Now `LWRadiance` uses class-level variables to hold global variables for variable names and mappings 
* The `LocMdata`, `VarMdata`, and `AttrData` were used as global variables but logically must be class member variables.
* Moved the `writer` object to the class
* Changed the `LWRadiance` constructor to take the center_datetime and the output_filename
* Now `readInFiles()` simply takes a list of filenames to process.
* Added `writeIODA()` to implement the file writing.
* Added mechanism to allow file to be executed from source, build or install directory (to be replaced with setup.py eventually)
* Reorganized headers
* Fixes for coding norms

I still require help from @weihanucar:

1. to reduce the size of the testing files included in this PR.  I just took a single file:
```
SSEC_V3.0.3_Z_SATE_C_BAWX_20200801005005_P_FY4A-_GIIRS-_N_REGX_1047E_L1-_IRD-_MULT_NUL_20200801004500_20200801005544_016KM_020V3.nc
```
Saved it as `testinput/giirs_ssec.nc` and converted it with date `2020080100` and saved the result as `testouput/giirs_ssec_ioda.nc4`.  I think these files are still much too big and we'll require a smaller example.

2. What is the relation of this software with the other `src/nsmc/giirs_lw2ioda.py`?

### CODE REVIEW

**Comment by srherbener** [comment]
@markjolah, @weihanucar thanks for adding this converter.

This looks like a companion to what's in the src/nsmc directory. The scripts in the src/nsmc directory output long wave (LW) radiation as the observation data, and this one converts the LW to brightness temperature (Tb) and outputs Tb as the observation data.

Perhaps this script could eventually be modified to handle both cases (LW radiation and Tb).

My recommendation is to combine this directory with the src/nsmc directory before merging.

**Comment by weihanucar** [comment]
#GIIRS preprocessing , SSEC reprocessed L1 data to IODA 
#Wei Han, 08/08/2020

Step1: collect ssec GIIRS  reprocessed files L1 dwell filenames into a file for 1 hour time slot
./prep_file_name.sh yyyymmddhh-begin yyyymmddhh-end
Example:
./prep_file_name.sh 2020050100 2020050200
Note:
input ssec GIIRS  reprocessed file path
path_input='/ships19/cma/production/FY4A/'

Step2: convert 2 hours GIIRS ssec reprocessed files to ioda netcdf
./giirs2nc_2h.sh yyyymmddhh-begin yyyymmddhh-end
Example:
./giirs2nc_2h.sh 2020050100 2020050200

The output giirs ioda files are :
giirs_fy4a_lw_ioda_2020050100.nc4  giirs_fy4a_lw_ioda_2020050112.nc4
giirs_fy4a_lw_ioda_2020050106.nc4  giirs_fy4a_lw_ioda_2020050118.nc4
giirs_fy4a_lw_ioda_2020050200.nc4

Note:
set the output ioda netcdf file path in giirs2nc_2h.sh,
e.g:path_giirs=/data/users/whan/data/obs/giirs_v3/ioda_2h_1

**Comment by markjolah** [comment]
@weihanucar Note that I made some slight changes to the interface to make it a bit more generic.  Instead of passing the path to a txt file which itself contains a list of files to process, this script just accepts a sequence files as input.  I will let you and @srherbener decide how to package this together with the other giirs script, as I am not familiar enough with the background of how they are related.

**Comment by srherbener** [comment]
My recommendation is to merge the src/giirs and src/nsmc directories together. To me these two sets appear to be strongly related. Since these are tools for SSEC at U Wisc, I propose merging these into a new directory called src/ssec.

How does that sound with you @weihanucar?

Also, @weihanucar there were a couple revised scripts (giirs_lw2ioda_bt_v1.py.new, giirs_lw2ioda_bt_v2.py.new) checked into the src/nsmc directory. Do you still need these? They appear to be earlier versions of the script that is contained in this PR, and if that is true I would like to delete them.

I can make the changes once we are agreed on what to do.

Thanks!

**Review by weihanucar — APPROVED** [review]

**Pull request merged**
