### PR TITLE
Fix ncep coding norms

### LINKED ISSUE #174: Fix coding norm and add file conversion test for NCEP scripts
The tool autopep8 can be used to automatically fix the coding norms test failures.

Use the marine test setup (test/CMakeLists.txt) as a guide to creating a new file conversion test.

### PR DESCRIPTION
**Pull request by aerorahul**
Fix ncep coding norms

closes #174 

Change-Id: Ide8b39a967b1d1965dfa1343ba98c12164a99bd5

### CODE REVIEW

**Comment by srherbener** [comment]
@aerorahul, thanks for starting the fix for the coding norms. I'll work on this now for a while to give you a break.

**Comment by aerorahul** [comment]
I am almost done @srherbner.
Watch out for a PR later tonight



________________________________
On: 16 May 2019 17:55, "Stephen Herbener" <notifications@github.com<mailto:notifications@github.com>> wrote:

@aerorahul<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_aerorahul&d=DwMCaQ&c=ApwzowJNAKKw3xye91w7BE1XMRKi2LN9kiMk5Csz9Zk&r=3OMHr3NdbTWC3g0Ab6ByEqzDD4l8q4wg8DACqqRz9W8&m=Str_FLM0Cmn--o7wbsW2HiWhztS4xsgboPqlv_m-CLg&s=iGXqG2nn1Crtm6abLUf5r3s-D5tVd1_CsWTNZB0ZS0Y&e=>, thanks for starting the fix for the coding norms. I'll work on this now for a while to give you a break.

**Comment by srherbener** [comment]
@aerorahul, okay. Thanks for letting me know.

**Comment by aerorahul** [comment]
@srherbener Please re-review now.

**Pull request merged**
