### PR TITLE
Clang for CodeBuild

### PR DESCRIPTION
**Pull request by mer-a-o**

### CODE REVIEW

**Comment by mer-a-o** [comment]
@srherbener: tests 6-18 fails in clang container. Looks like the error is related to ```nccmp``` as you guessed. 
```
6: nccmp: error while loading shared libraries: libnetcdf.so.15: cannot open shared object file: No such file or directory 
```
I use ```jcsda/docker-clang-mpich-dev:latest container``` in CodeBuild 
I cannot reproduce the error on my laptop inside the Docker container though.

**Comment by srherbener** [comment]
@mer-a-o, this is a different error that what I saw before, but by coincidence with the same program (nccmp). It looks like the nccmp is loading the wrong netcdf library (ie, a version that is different than the one it was built with).

Python installs the netcdf library version that goes with the netCDF4 python package. It's possible that nccmp is accidentally finding the Python netcdf libraries and these could be different than the versions that nccmp was built with. Python should be installing these in /usr/local/lib/python3 or /usr/local/lib/python3/site-packages. If the Python path is on LD_LIBRARY_PATH before /usr/local/lib, then that would cause this situation.

**Comment by mer-a-o** [comment]
@srherbener Thanks for the comment. I removed mpi setup steps I use for gnu/mpi container from clang yml and it fixed the problem! Now all 3 aws CodeBuild tests pass for Ioda-converters. I will add the clang badge to README.md and then it will be ready for merge.

**Comment by mmiesch** [comment]
great - thank you both for figuring this out!

**Pull request merged**
