### PR TITLE
Feature/mcs ncep bufr sf

### PR DESCRIPTION
**Pull request by flampouris**
This is the converter from Bufr to NC4

To test it, run it: 

python3 ncep_classes.py -m 1 -p ./ -i xx120 -ot NC031120 -d 2019031000

Please, check it and let me know, it needs documentation.

Thank you

### CODE REVIEW

**Comment by srherbener** [comment]
@flampouris, were you meaning to have the target branch be "develop" or "feature/marine-cs-03-2019"? This PR is targeting develop and attempting to pull in most of the feature/marine-cs-03-2019 changes with it, which we probably don't want to do until after the code sprint.

It's easy to change the target branch. Just hit the "Edit" button in the upper-right (near the PR title), and then the message "@flampouris wants to merge 49 commits into develop from feature/mcs-NcepBufr-sf" should change so that you can pull down on "develop" and select "feature/marine-cs-03-2019".

Thanks!

**Comment by flampouris** [comment]
@srherbener  I changed the target of PR to the feature/marine-cs-03-2019 branch

**Comment by flampouris** [comment]
@srherbener the branch has been updated according to our discussion. Please check it for the PR.

**Comment by svahl991** [comment]
Is there a specific reason my review was requested on this? This doesn't appear to deal with files I'm super familiar with.

**Comment by flampouris** [comment]
Hi @svahl991, you were added as a reviewer because yaml files are used for the dictionary, I am just removing you from the reviewers' list.

**Comment by svahl991** [comment]
Ah. Since I knew what you were requesting, I did take a look at your YAML. It can certainly work the way you have it, but you appear to be using nested YAML lists for everything, including some places where your data might be a better fit for a YAML dictionary <key, value> structure. If you want, you can look in the ioda-converters/src/ODB2/Definitions directory, where I have a few YAML files that work with my converter. They have lists in some places and dictionaries in others. But if you already have working code with your structure, it's probably not worth changing unless you want to.

**Pull request merged**
