### PR TITLE
       deleted:    ../src/marine/cryosat_ice2ioda_DBL.py

### PR DESCRIPTION
**Pull request by YanHao-NOAA**
ESA reprocessed all the cryosat-ice data to baseline D.  All the .DBL formatted files were converted into NetCDF files. 
       We can delete cryosat_ice_DBL converter from ioda-converters.

       modified:   ../test/CMakeLists.txt
       deleted:    ../test/testinput/CS_OFFL_SIR_GDR_2__20160229T132459_20160229T150412_C001.DBL
       deleted:    ../test/testoutput/cryosat2_L2_DBL.nc
       modified:  src/marine/CMakeLists.txt
       deleted:   read_cryosat_L2.py  from  src/lib-python
       modified:  src/lib-python/CMakeLists.txt

### CODE REVIEW

**Comment by YanHao-NOAA** [comment]
Update: I forgot to rm read_cryosat_L2.py in /src/lib-python, now it is deleted.

**Comment by YanHao-NOAA** [comment]
> It looks ok to remove ice dbl converter. I hope to see some description for PR but I am ok to approve.

Thank you, I added more description for PR.

**Comment by YanHao-NOAA** [comment]
> Thanks for doing this @YanHao-NOAA . You need to remove this file name from [the src/marine/CMakeLists.txt](https://github.com/JCSDA/ioda-converters/blob/adb735d50a943606b8ed285b1b93b5f7864e6a5c/src/marine/CMakeLists.txt#L3)

Thank you, I removed 

> Thanks for doing this @YanHao-NOAA . You need to remove this file name from [the src/marine/CMakeLists.txt](https://github.com/JCSDA/ioda-converters/blob/adb735d50a943606b8ed285b1b93b5f7864e6a5c/src/marine/CMakeLists.txt#L3)

Thank you, I removed cryosat_ice2ioda_DBL.py from the List in the file src/marine/CMakeLists.txt

**Comment by guillaumevernieres** [comment]
@YanHao-NOAA , Assuming that you don't need `read_cryosat_L2.py` , you also need to remove it from the cmakelists.txt.

**Comment by YanHao-NOAA** [comment]
> @YanHao-NOAA , Assuming that you don't need `read_cryosat_L2.py` , you also need to remove it from the cmakelists.txt.
Thanks again. I removed read_cryosat_L2.py from the cmakelist. I did not notice there is another cmakelist in lib-python.

**Comment by YanHao-NOAA** [comment]
> Thanks for taking care of this!

You are welcome!

**Pull request merged**
