### PR TITLE
feat: add option to use monetio to download/read aeronet data for ioda

### PR DESCRIPTION
**Pull request by bbakernoaa**
This feature adds the ability to read and or retrieve aeronet data
using the Model and Observation Evaluation Tool I/O (monetio).
monetio is available at https://github.com/noaa-oar-arl/monetio.

The function can read either the AOD level 1.5 or AOD level 2.0
data from AERONET.

### CODE REVIEW

**Comment by srherbener** [comment]
@bbakernoaa, we have a configuration issue with the automatic testing of which @mer-a-o has a PR in the works to fix. The automatic testing should be back up soon.

I downloaded your feature branch and tested on my iMac. The ``iodaconv_chem_coding_norms`` test failed, with the following messages:

```
    Start 4: iodaconv_chem_coding_norms

4: Test command: /Users/stephenh/projects/ioda-converters/build/bin/iodaconv_lint.sh "/Users/stephenh/projects/ioda-converters/src/chem" "/Users/stephenh/projects/ioda-converters"
4: Environment variables:
4:  OMP_NUM_THREADS=1
4: Test timeout computed to be: 1500
4: + SRC_DIR=/Users/stephenh/projects/ioda-converters/src/chem
4: + PYCODESTYLE_CFG_PATH=/Users/stephenh/projects/ioda-converters
4: + cd /Users/stephenh/projects/ioda-converters/src/chem
4: + pycodestyle -v --config=/Users/stephenh/projects/ioda-converters/.pycodestyle '--filename=*.py,*.py.in' .
4: cli configuration: /Users/stephenh/projects/ioda-converters/.pycodestyle
4: directory .
4: checking ./monet_aeronet2ioda.py
4: ./monet_aeronet2ioda.py:19:1: E302 expected 2 blank lines, found 1
4: ./monet_aeronet2ioda.py:21:9: E225 missing whitespace around operator
4: ./monet_aeronet2ioda.py:40:17: E231 missing whitespace after ','
4: ./monet_aeronet2ioda.py:44:26: E231 missing whitespace after ','
4: ./monet_aeronet2ioda.py:45:52: W291 trailing whitespace
4: ./monet_aeronet2ioda.py:46:54: W291 trailing whitespace
4: ./monet_aeronet2ioda.py:51:14: E231 missing whitespace after ','
4: ./monet_aeronet2ioda.py:52:26: E231 missing whitespace after ':'
4: ./monet_aeronet2ioda.py:54:110: E202 whitespace before ')'
4: ./monet_aeronet2ioda.py:55:101: E225 missing whitespace around operator
4: ./monet_aeronet2ioda.py:56:98: E225 missing whitespace around operator
4: ./monet_aeronet2ioda.py:62:26: E231 missing whitespace after ','
4: ./monet_aeronet2ioda.py:65:26: E225 missing whitespace around operator
4: ./monet_aeronet2ioda.py:73:1: E302 expected 2 blank lines, found 1
4: ./monet_aeronet2ioda.py:80:20: E222 multiple spaces after operator
4: ./monet_aeronet2ioda.py:81:6: E901 IndentationError: unindent does not match any outer indentation level
4: checking ./viirs_aod2ioda.py.in
4: 1       E202 whitespace before ')'
4: 1       E222 multiple spaces after operator
4: 4       E225 missing whitespace around operator
4: 5       E231 missing whitespace after ','
4: 2       E302 expected 2 blank lines, found 1
4: 1       E901 IndentationError: unindent does not match any outer indentation level
4: 2       W291 trailing whitespace
1/1 Test #4: iodaconv_chem_coding_norms .......***Failed    0.14 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
iodaconv    =   0.14 sec*proc (1 test)
script      =   0.14 sec*proc (1 test)

Total Test time (real) =   0.15 sec

The following tests FAILED:
	  4 - iodaconv_chem_coding_norms (Failed)
Errors while running CTest
```

Not sure why this test passes in the auto testing checks. Could be that my iMac has a newer version of pycodestyle (python coding style checker). My iMac has version 2.6.0 (latest) of pycodestyle.

I am going to be on vacation next week, and if you are okay with waiting we can pick up on this when I'm back. Otherwise, you may want to assign another reviewer such as @markjolah or @mmiesch.

Thanks!

**Comment by srherbener** [comment]
@bbakernoaa, I just merged in @mer-a-o's fix for the auto testing in to the develop branch. Please update your fork with the new develop branch and merge into your feature/monet_aeronet branch. This should trigger a new test cycle which should successfully run the tests. Then we can proceed after we see the results of the tests. Thanks!

**Comment by bbakernoaa** [comment]
Ok I'll get this going soon. Thanks

**Comment by srherbener** [comment]
@mer-a-o, it looks like the auto testing is not picking up the feature brach for this PR. I think the issue is that the feature brach is coming from a fork that @bbakernoaa created for his local clone, and as a consequence the test setup is not finding it.

I think the CodeBuild tests are passing because they are running on develop, since they cannot find the feature branch in @bbakernoaa's fork (CODEBUILD_GIT_BRANCH is not getting set).

If you expect the test setup to be working with a PR from a fork, perhaps the fault is due to something that isn't configured correctly with this repo. I can take a look at that.

Thanks @mer-a-o for helping with this!

**Comment by srherbener** [comment]
@bbakernoaa, it turns out that the auto testing can't yet handle testing feature branches from a fork. This capability is required and it's on the to-do list, but we won't be able to get to it for a while. I think the best way to move forward is to switch to a clone of this repository and issue a new PR from the clone. It looks like you have permission to push feature branches directly to this repository so this should work.

Since there are only 2 files to deal with, I think the easiest and safest way to do this is to create a fresh clone in a new directory on your side, start a new feature branch in the clone, and then copy the changes from the fork to the clone. Then publish (push) the new feature branch from the clone to this repository.

Once that is done, close this PR and submit a new PR from the new feature branch (that came from your clone). You can still access this PR after it is closed (in case you want to copy and paste the description).

Sorry about the inconvenience, and your patience with this is much appreciated.

Thanks!

**Comment by bbakernoaa** [comment]
No problem

**Pull request closed without merging**
