### PR TITLE
set of functions for common meteorological utilities for creators of IODA-ready data files

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
A set of functions that may assist others in creating new variables from other ones when preparing IODA-ready data/files. Where possible, attribution to the source of the function is provided in comments.  If needed by specific centers/users, we can create a series of functions that may have alternative forms of higher or lower accuracy.  A good example is found in the function called "e_sub_s" that computes saturation vapor pressure or liquid (another function for ice) and there are 2 alternatives in comments to permit other relationships.  In that case, perhaps a form of Case/Switch block code construct can provide access to alternates.

### CODE REVIEW

**Comment by srherbener** [comment]
Please add an entry for the `meteo_utils.py` module in the `src/lib-python/CMakeLists.txt` file. All you need to do is add `meteo_utils.py` to the list at the top of the CMakeLists.txt file:

```
list( APPEND libs
  ioda_conv_ncio.py
  ioda_conv_util.py
  collect_sources.py
  meteo_utils.py  <-- Add meteo_utils.py here
  orddicts.py
)
.
.
.
```

By doing this, it will enable installing the `meteo_utils.py` module when `make install` is run.

Thanks!

**Comment by gthompsnJCSDA** [comment]
@srherbener  Could you ensure that my latest Git-push achieved the desired result?  I think it's now complete.  Thanks!

**Comment by srherbener** [comment]
@gthompsnJCSDA thanks for updating. I can do `make install` and I can set PYTHONPATH to my install location and successfully run an `import meteo_utils`. Here's what I did:

```
# build, test and install
ecbuild -DCMAKE_INSTALL_PREFIX=$HOME/install/ioda-converters ..
make
ctest
make install

# import
PYTHONPATH=$HOME/install/ioda-converters/lib/pyiodaconv python3
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import meteo_utils
>>>
```

Is this the intended usage, i.e to import the module and start using the methods it contains. If so, I can't seem to be able to instantiate an object of the meteo_utils class. I think this so because the meteo_utils class is missing an `__init__` constructor method.

Or is there a different usage you had in mind?

**Comment by gthompsnJCSDA** [comment]
@srherbener  I have another piece of Python code that I wrote for converting some CSV-formatted surface obs (METARs) into a IODA netCDF file.  In that code (not entered into any repo yet), I just use the import meteo_utils near the top and internal to a function of that code, I have a line such as this:
   uwnd,vwnd = self.meteo_utils.dir_speed_2_uv(wdir, wspd)
to perform the method/function.

I am still very new to Python so my test code works, but I don't exactly know where to put the 'constructor' and if it is needed considering I can call its functions just by using the import command at the top of my calling code.

Feel free to suggest any improvement(s).

**Comment by srherbener** [comment]
@gthompsnJCSDA I took the liberty (hope that was okay) to edit the meteo_utils class so that it can be instantiated as an object in the script that imports the meteo_utils module. Here's an example of how it can be used:

```
sysadmins-iMac:build stephenh$ PYTHONPATH=$HOME/install/ioda-converters/lib/pyiodaconv python3
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import meteo_utils as met
>>> metUtils = met.meteo_utils()
>>> metUtils.std_atmos(50000)
5564.332842055986
>>> metUtils.STP_P
101320.7888
>>> metUtils.std_atmos(metUtils.STP_P)
0.3498881987294075
>>>
```

If that looks okay with you, the only thing left is to fix the coding style errors. You can run `ctest -VV -R lib-python_coding` from the command line to get a list of what needs to be fixed.

**Comment by gthompsnJCSDA** [comment]
@srherbener  I feel dumb. I tried running that ctest lib-python_code command in the top-level ioda-converters dir, then in the src/lib-python dir, then in the test subdir and I get the same result:  "Added 0 tests to meet fixture requirements...No tests were found."  Where do I need to be when issuing the ctest command?

**Comment by srherbener** [comment]
@gthompsnJCSDA you should be able to run `ctest` from your build directory which is the place where you ran `ecbuild` or `cmake`. You've probably got a bunch of Testing directories sprinkled in your source area. You may want to start over from scratch. Here's the sequence:

```
git clone https://github.com/JCSDA/ioda-converters.git
cd ioda-converters
git checkout feature/add_meteo_utils_functions
mkdir build
cd build
ecbuild ..   # the argument to ecbuild is a path to where the source is located
make -j4
ctest

ctest -VV -R lib-python_coding 
```

**Comment by gthompsnJCSDA** [comment]
@srherbener  OK, I resolved the items for coding-norms.  Not a fan of some of these norms, because some are just too stringent and strange, but OK, will live with it.  Hopefully all blockades now resolved. Thanks for helping.

**Comment by srherbener** [comment]
@gthompsnJCSDA in light of today's weekly meeting, I wonder if this module belongs in the new JCSDA/solo repository. Moving it to the solo repo would make it available to a wider audience. What do you think?

**Comment by gthompsnJCSDA** [comment]
> @gthompsnJCSDA in light of today's weekly meeting, I wonder if this module belongs in the new JCSDA/solo repository. Moving it to the solo repo would make it available to a wider audience. What do you think?


Steve, I don't know what you mean by a "solo" repository.  I am pretty open to wherever it lands and agree that the widest possible use amongst anything JEDI is best.  It will need further contributions for more functions/methods and an internal way to switch some specific choice inside - that's my belief anyway.  So a RH calculator (as an example) could use one of 3 internal choices as I've documented in the "e_sub_s" function since there are many legacy codes for handling moisture variables in particular.

**Comment by srherbener** [comment]
@gthompsnJCSDA, sorry about the confusion. What I mean by "solo repo" is Claude's new JCSDA/solo repository (named after Han Solo in keeping with the Star Wars theme). JCSDA/solo is intended to be a repository of handy python modules/routines that will be built and distributed as its own python package of which any python script in other repos (such as ioda-converters) can use. That's why I'm saying that JCSDA/solo would be a means for making your routines available to a wider audience.

**Review by rhoneyager — APPROVED** [review]

**Pull request merged**
