### PR TITLE
Remove the use nrecs from ioda obs file

### PR DESCRIPTION
**Pull request by emilyhcliu**
List of work performed in this PR:

(1) Removed the use of nrecs from IODA obs file
      Files modified:
- /src/**gsi_ncdiag**/gsi_ncdiag.py
-  /src/**lib-python**/ioda_conv_ncio.py

(2) Updated  all python scripts under **marine** directory according to changes in (1)

(3) Updated all related output test observation files (**test/testoutput**) according to changes in (1) and confirmed that the nrecs were removed.

### CODE REVIEW

**Comment by markjolah** [comment]
@emilyhcliu Great!  I will test this out today.

**Comment by srherbener** [comment]
@emilyhcliu, thanks for getting your updates into PRs so quickly.

I spoke with @hailingz today about the use of nrecs for the GNSSRO operators and we determined that it is okay to remove nrecs and variables dimensioned by nrecs from the obs files.

On another note, github is reporting a conflict with the amsua_aqua_obs_2018041500.nc4 file. Could you look into this? Thanks!

**Comment by emilyhcliu** [comment]
@srherbener 
I just found out that I forgot to update my branch with develop before I added modifications.  So, I am going to re-do the branch and then submit a new PR.  I will close this one and submit a new one in an hour.  Sorry about this.

**Comment by srherbener** [comment]
@emilyhcliu, rather than creating a new branch, would it be easier to merge develop into this branch?

**Pull request closed without merging**
